import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  safeAreContainer: {
    backgroundColor: '#d3d3d3',
    flex: 1,
  },
  TitleContainer: {
    width: '100%',
    height: 40,
    marginBottom: 15,
    marginTop: 8,
    alignItems: 'center',
  },
  headContainer: {
    fontSize: 35,
    fontWeight: 'bold',
    color: '#191970',
  },
  noteContainer: {
    backgroundColor: '#c0c0c0',
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: '#00008b',
    width: '97%',
    height: 80,
    marginLeft: 5,

    flexDirection: 'row',
  },
  noteTextContainer: {
    flexDirection: 'row',
    marginLeft: 14,
    marginTop: 25,
    fontSize: 22,
    fontWeight: 330,
  },
  icon: {
    width: 16,
    height: 16,
    borderRadius: 100,
    backgroundColor: '#c0c0c0',
    borderWidth: 1.4,
    borderColor: '#00008b',
    marginTop: 30,
    marginLeft: 25,
  },
  deleteViewContainer: {
    backgroundColor: '#c0c0c0',
    borderWidth: 0.5,
    borderColor: '#191970',
    width: 35,
    height: 30,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: -70,
  },
  deleteTextContainer: {
    color: '#dc143c',
    fontSize: 15,
    fontWeight: 600,
  },
  container: {
    flexDirection: 'row',
    marginTop: 5,
  },
  direction: {
    height: 80,
    justifyContent: 'center',
    padding: 5,
    margin: 1,
  },
  allContainerText: {
    marginTop: 380,
    backgroundColor: '#c0c0c0',
    borderWidth: 0.5,
    borderColor: '#00008b',
    borderRadius: 20,
    margin: 8,
  },
  buttonViewTextContainer: {
    backgroundColor: '#a9a9a9',
    padding: 10,
    borderRadius: 50,
    marginHorizontal: 20,
    marginBottom: 5,
    marginTop: 5,
    borderWidth: 0.5,
    borderColor: '#00008b',
    alignItems: 'center',
  },
  buttonTextContainer: {
    color: '#00008b',
    padding: 7,
    fontSize: 18,
    alignItems: 'center',
  },
  textInputContainer: {
    backgroundColor: '#c0c0c0',
    height: 55,
    borderBottomWidth: 0.5,
    borderColor: '#00008b',
    width: '100%',
    padding: 15,
    color: '#00008b',
    fontSize: 20,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  keybordContainer: {},
});
export default styles;
